spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&useSSL=false&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.163.com
    username: jhh13115147529@163.com
    password: KXKOPCKUUTJZAPOU
  redis:
    database: 5
logging:
    level:
      com.javasm.springbootmybatis: debug

